version: '3.1'

services:
  mongo:
    container_name: mongodb5
    image: mongo:5.0.13
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k9bKWQZPemVC_E2fDBpRgHML
      MONGO_INITDB_DATABASE: DB001
    volumes:
      - ./mongodb_server_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js