version: '3.1'

services:
  mongo:
    image: mongo:5.0.13
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: k9bKWQZPemVC_E2fDBpRgHML
      MONGO_INITDB_DATABASE: DB001
    volumes:
      - ./mongodb_server_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: k9bKWQZPemVC_E2fDBpRgHML
      ME_CONFIG_MONGODB_URL: mongodb://root:k9bKWQZPemVC_E2fDBpRgHML@mongo:27017/
    links:
      - mongo

